<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v1.GetResponse</code>
 */
class GetResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string metrics = 1;</code>
     */
    private $metrics = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $metrics
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string metrics = 1;</code>
     * @return string
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    /**
     * Generated from protobuf field <code>string metrics = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMetrics($var)
    {
        GPBUtil::checkString($var, True);
        $this->metrics = $var;

        return $this;
    }

}

